services:
  kiwinews:
    build:
      context: .
    image: kiwinews.kiwinews.public.dappnode.eth:0.0.1
    restart: unless-stopped
    volumes:
      - type: volume
        source: bootstrap
        target: /app/bootstrap
      - type: volume
        source: cache
        target: /app/cache
      - type: bind
        source: .env
        target: /app/.env
    ports:
      - "3000:3000"
      - "8443:8443"
      - "53462:53462"

volumes:
  bootstrap:
  cache:

